---
Name: mysite
After:
  0: 'framework/*'
  1: 'cms/*'
i18n:
  default_locale: en_NZ
Database:
  name: ss_databasename
SSViewer:
  theme: base
GDBackend:
  default_quality: 90
SiteConfig:
  extensions:
    - CustomSiteConfig
    - TrackingConfig
UserDefinedForm_EmailRecipient:
  allow_unbound_recipient_fields: true
# Mailgun integration
SmtpMailer:
  host: smtp.mailgun.org
  user:
  password:
  tls: true
  charset: UTF-8
